### ISSUE TITLE
osu-lazer failing to install

### ISSUE THREAD

**Issue by zxcv1245** [TheGreatMcPain/TheGreatMcPain-overlay#10]
The osu-lazer ebuild fails on a clean system.

**emerge osu-lazer**
https://hastebin.com/gujizomiwo

**emerge --info '=games-arcade/osu-lazer-9999.999.9::lanodanOverlay'**
https://hastebin.com/apivamijaq

**Comment by TheGreatMcPain** [comment]
The osu-lazer you where emerging is not in this overlay.

try `osu-lazer::thegreatmcpain-overlay`

**Comment by TheGreatMcPain** [comment]
Quick note though.

The error you were seeing was because the `network-sandbox` FEATURE was not disabled for `osu-lazer` which prevents it from accessing the internet.

You can disable `network-sandbox` by creating a file in `/etc/portage/env` such as `disable-network-sandbox` with this inside.
```
FEATURE="-network-sandbox"
```

Then create a file in `/etc/portage/package.env` and add this to it.
```
games-arcade/osu-lazer disable-network-sandbox
```

**Comment by zxcv1245** [comment]
Oh, I'm really sorry. How could I not notice that I was emerging the wrong package.
I'm currently still emerging the one from your overlay, thanks for the advice.

**Comment by zxcv1245** [comment]
Your ebuild fails too, but disabling the network-sandbox FEATURE solves the problem. 
https://hastebin.com/uqutasezar

Also I assume you've made a typo, as the correct way is using FEATURE**S**.
`FEATURES="-network-sandbox"`

**Comment by TheGreatMcPain** [comment]
Yup, I made a typo.

Also, the ebuild is supposed to fail if `network-sandbox` is enabled.
