### ISSUE TITLE
osu-lazer certificate issue

### ISSUE THREAD

**Issue by RaphaelNeubert** [TheGreatMcPain/TheGreatMcPain-overlay#9]
For some reason the 9999 build wouldn't open anymore and i was just stuck in a blackscreen upon launching the game.
I wasn't sure what the issue was so i just tried to update the game but the update failed and i was getting tons of red lines mostly about certificate stuff. I've also tried it with the 2021424 version. Here is what i've tried to fix it.

>Updated the package `ca-certificates`
>Updated the certificates with `sudo update-ca-certificates`
>removed and reinstalled the package (removed it with  `emerge -C ca-certificates` because it was a dependency of other packages)
>made sure i had  the newest version of your repository
>enabled the useflag `cacert`

All of this without success. 
Here is my build log:

[build.log](https://github.com/TheGreatMcPain/TheGreatMcPain-overlay/files/6474551/build.log)

**Comment by TheGreatMcPain** [comment]
What version of `dotnetcore-sdk-bin` do you have?

**Comment by RaphaelNeubert** [comment]
`dev-dotnet/dotnetcore-sdk-bin-5.0.201:5.0::thegreatmcpain`

**Comment by TheGreatMcPain** [comment]
Update it.

New version has a workaround for the ca-certification issues.

**Comment by RaphaelNeubert** [comment]
Thanks that fixed it. I thought the ebuild would pull all the right versions.

Sadly osu-lazer still opens with a black screen which is weird because it used to work. 
Can you confirm that it works for you? I guess i should try to get help on osu-lazers github page.

**Comment by TheGreatMcPain** [comment]
Well, the reason for the issue is due to a [certificate update on Microsoft's end](https://github.com/NuGet/Announcements/issues/49) which caused issues on `ca-certificates`'s end which upstream hasn't fully resolved yet. It used to work fine using an older version of `ca-certificates` while the latest version doesn't work.

So, dotnet's upstream decided to completely disable trusted certificates in the latest version of dotnetcore as a temporary workaround.

Technically osu can be built with any version of dotnetcore 5 it's only recently there has been issues related to certificates.

I'll go ahead and drop the old versions of dotnetcore anyway.

Also, I can confirm that the game works fine on both my desktop (nvidia gpu) and laptop (intel hd graphics).
